### ISSUE TITLE
Connection reset using traci4matlab

### ISSUE THREAD

**Issue by JustinMue** [pipeacosta/traci4matlab#16]
So I can run simple simulations of up to 600 steps in TraCI but as I have for example a simulation of up to 1800 steps, at some point the simulation (not always on the same step) crashes due to (probably) connection loss to the sumo server. Matlab as the TraCI user tells me then:

Java exception occurred:
java.net.SocketException: Connection reset

at java.net.SocketInputStream.read(SocketInputStream.java:210)

at java.net.SocketInputStream.read(SocketInputStream.java:141)

at java.net.SocketInputStream.read(SocketInputStream.java:224)

at java.io.DataInputStream.readInt(DataInputStream.java:387)
Java should be on the latest update...
The simulation itself goes on for maybe half an hour, because every step has to be computed by some algorithm. So maybe the whole simulation time itself is causing connection issues?
This topic has been here already but closed on #6248, hopefully someone can help?
(Sumo Version 1.7.0 TraCI: '20')
Thanks 
![Matlab_errorCode](https://user-images.githubusercontent.com/80890452/111819740-ffc3b580-88e0-11eb-9aaa-a2bfdd837db2.PNG)

**Comment by xunliusimon** [comment]
Hi Justin, I also meet this problem today, have you solved this issue?
