### ISSUE TITLE
Java connection issue

### ISSUE THREAD

**Issue by prasuka4** [pipeacosta/traci4matlab#27]
Hi,
I have following issue to run the traci4matlab.
I have installed as per the documentation but java connection issue is not allowing to proceed.

Could not connect to TraCI server at 127.0.0.1:≭. Undefined function 'DataReader' for input arguments of type 'java.io.DataInputStream'.
Error using traci.Socket/connect
Java exception occurred:
java.net.ConnectException: Connection refused: connect

	at java.net.DualStackPlainSocketImpl.connect0(Native Method)

	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)

	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)

	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

	at java.net.Socket.connect(Socket.java:589)

	at java.net.Socket.connect(Socket.java:538)

Error in traci.connect (line 44)
        c.connect(host, port);

Error in traci.start (line 62)
connections(label) = traci.connect(port, numRetries, host);

Error in inter_palmas_actuated (line 23)
traci.start('sumo-gui -c ./inter_palmas_actuated.sumocfg --start');
Could not connect to TraCI server at 127.0.0.1:≭. Java exception occurred: 
java.net.SocketException: Socket is not connected

could you please resolve this

**Comment by cx1231231** [comment]
我也遇到了，解决了吗
