### ISSUE TITLE
traci4matlab  installation failed

### ISSUE THREAD

**Issue by shuowang572875852** [pipeacosta/traci4matlab#4]
After installing traci4matlab, running traci_test.m has the following error:
错误使用 traci.Socket/connect (line 25)
Java exception occurred:
java.net.ConnectException: Connection refused: connect

at java.net.DualStackPlainSocketImpl.connect0(Native Method)

at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)

at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

at java.net.Socket.connect(Socket.java:589)

at java.net.Socket.connect(Socket.java:538)
出错 matlab.internal.lang.fwdSubsref (line 4)
[varargout{1:nargout}] = subsref(A,s);

出错 traci.init (line 65)
connections(label).connect(host, port);

出错 traci_test (line 24)
[traciVersion,sumoVersion] = traci.init();
错误使用 traci.Socket/connect (line 25)
Java exception occurred:
java.net.ConnectException: Connection refused: connect

at java.net.DualStackPlainSocketImpl.connect0(Native Method)

at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)

at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

at java.net.Socket.connect(Socket.java:589)

at java.net.Socket.connect(Socket.java:538)
出错 matlab.internal.lang.fwdSubsref (line 4)
[varargout{1:nargout}] = subsref(A,s);

出错 traci.init (line 65)
connections(label).connect(host, port);

出错 traci_test (line 24)
[traciVersion,sumoVersion] = traci.init();
错误使用 traci.Socket/connect (line 25)
Java exception occurred:
java.net.ConnectException: Connection refused: connect

at java.net.DualStackPlainSocketImpl.connect0(Native Method)

at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)

at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

at java.net.Socket.connect(Socket.java:589)

at java.net.Socket.connect(Socket.java:538)
出错 matlab.internal.lang.fwdSubsref (line 4)
[varargout{1:nargout}] = subsref(A,s);

出错 traci.init (line 65)
connections(label).connect(host, port);

出错 traci_test (line 24)
[traciVersion,sumoVersion] = traci.init();
错误使用 traci.Socket/connect (line 25)
Java exception occurred:
java.net.ConnectException: Connection refused: connect

at java.net.DualStackPlainSocketImpl.connect0(Native Method)

at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)

at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

at java.net.Socket.connect(Socket.java:589)

at java.net.Socket.connect(Socket.java:538)
出错 matlab.internal.lang.fwdSubsref (line 4)
[varargout{1:nargout}] = subsref(A,s);

出错 traci.init (line 65)
connections(label).connect(host, port);

出错 traci_test (line 24)
[traciVersion,sumoVersion] = traci.init();
错误使用 traci.Socket/connect (line 25)
Java exception occurred:
java.net.ConnectException: Connection refused: connect

at java.net.DualStackPlainSocketImpl.connect0(Native Method)

at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)

at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

at java.net.Socket.connect(Socket.java:589)

at java.net.Socket.connect(Socket.java:538)
出错 matlab.internal.lang.fwdSubsref (line 4)
[varargout{1:nargout}] = subsref(A,s);

出错 traci.init (line 65)
connections(label).connect(host, port);

出错 traci_test (line 24)
[traciVersion,sumoVersion] = traci.init();
错误使用 traci.Socket/connect (line 25)
Java exception occurred:
java.net.ConnectException: Connection refused: connect

at java.net.DualStackPlainSocketImpl.connect0(Native Method)

at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)

at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

at java.net.Socket.connect(Socket.java:589)

at java.net.Socket.connect(Socket.java:538)
出错 matlab.internal.lang.fwdSubsref (line 4)
[varargout{1:nargout}] = subsref(A,s);

出错 traci.init (line 65)
connections(label).connect(host, port);

出错 traci_test (line 24)
[traciVersion,sumoVersion] = traci.init();
错误使用 traci.Socket/connect (line 25)
Java exception occurred:
java.net.ConnectException: Connection refused: connect

at java.net.DualStackPlainSocketImpl.connect0(Native Method)

at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)

at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

at java.net.Socket.connect(Socket.java:589)

at java.net.Socket.connect(Socket.java:538)
出错 matlab.internal.lang.fwdSubsref (line 4)
[varargout{1:nargout}] = subsref(A,s);

出错 traci.init (line 65)
connections(label).connect(host, port);

出错 traci_test (line 24)
[traciVersion,sumoVersion] = traci.init();
错误使用 traci.Socket/connect (line 25)
Java exception occurred:
java.net.ConnectException: Connection refused: connect

at java.net.DualStackPlainSocketImpl.connect0(Native Method)

at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)

at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

at java.net.Socket.connect(Socket.java:589)

at java.net.Socket.connect(Socket.java:538)
出错 matlab.internal.lang.fwdSubsref (line 4)
[varargout{1:nargout}] = subsref(A,s);

出错 traci.init (line 65)
connections(label).connect(host, port);

出错 traci_test (line 24)
[traciVersion,sumoVersion] = traci.init();
错误使用 traci.Socket/connect (line 25)
Java exception occurred:
java.net.ConnectException: Connection refused: connect

at java.net.DualStackPlainSocketImpl.connect0(Native Method)

at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)

at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

at java.net.Socket.connect(Socket.java:589)

at java.net.Socket.connect(Socket.java:538)
出错 matlab.internal.lang.fwdSubsref (line 4)
[varargout{1:nargout}] = subsref(A,s);

出错 traci.init (line 65)
connections(label).connect(host, port);

出错 traci_test (line 24)
[traciVersion,sumoVersion] = traci.init();
错误使用 traci.Socket/connect (line 25)
Java exception occurred:
java.net.ConnectException: Connection refused: connect

at java.net.DualStackPlainSocketImpl.connect0(Native Method)

at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)

at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

at java.net.Socket.connect(Socket.java:589)

at java.net.Socket.connect(Socket.java:538)
出错 matlab.internal.lang.fwdSubsref (line 4)
[varargout{1:nargout}] = subsref(A,s);

出错 traci.init (line 65)
connections(label).connect(host, port);

出错 traci_test (line 24)
[traciVersion,sumoVersion] = traci.init();
MATLAB:Java:GenericExceptionJava exception occurred:
java.net.SocketException: Socket is not connected

at java.net.Socket.getInputStream(Socket.java:905)
结构体内容引用自非结构体数组对象。

出错 traci.sendExact (line 19)
activeConnection.dos.writeInt(len);

出错 traci.getVersion (line 23)
result = traci.sendExact();

出错 traci.init

出错 traci_test (line 24)
[traciVersion,sumoVersion] = traci.init();

and the commandline display :
Loading configuration... done.
***Starting server on port 8873 ***
Error: tcpip::Socket::accept() Unable to create listening socket: Address already in use
Quitting (on error).

D:\Program Files\matlab\R2017b\toolbox\traci4matlab\traci4matlab\examples>

During the installation process in Step 3"Adding the additional dependencies to the Matlab’s static
Java path", my javaclasspath.txt is
"D:\Program Files\matlab\R2017b\toolbox\traci4matlab\traci4matlab\traci4matlab.jar"
and the "D:\Program Files\matlab\R2017b\toolbox\traci4matlab\traci4matlab" is the path to the root folder of TraCI4Matlab.
How can i do for it?

**Comment by harsh7595** [comment]
Hi,

Use the following modified version of test.m

`
%% SUMO TRACI TEST
% THIS FILE AIMS TO TEST THE TRACI PROTOCOL FOR SUMO.

%   Authors: Andres Acosta, Jairo Espinosa, Jorge Espinosa.
%   Modified by: Harsh Shah, Ohio State University, USA
%   $Id: traci_test.m Jan, 17, 2020

clear
close all
clc

%% MAIN
% HERE, WE START THE SUMO SIMULATOR AND INITIALIZE IT, ACCORDING TO
% THE EXAMPLE FOUND IN http://sumo-sim.org/userdoc/Tutorials/TraCI4Traffic_Lights.html

scenarioPath = './inter_palmas/tls_actuated/inter_palmas_actuated.sumocfg ';


[traciVersion,sumoVersion] = traci.start(['sumo -c ' '"' scenarioPath '"' ' --start']);
traci.close();
fprintf('SUMO version: %s\n TraCI version: %d\n',sumoVersion,traciVersion);`

**Comment by harsh7595** [comment]
Hi,

Use the following modified version of test.m

`
%% SUMO TRACI TEST
% THIS FILE AIMS TO TEST THE TRACI PROTOCOL FOR SUMO.

% Authors: Andres Acosta, Jairo Espinosa, Jorge Espinosa.
% Modified by: Harsh Shah, Ohio State University, USA
% $Id: traci_test.m Jan, 17, 2020

clear
close all
clc

%% MAIN
% HERE, WE START THE SUMO SIMULATOR AND INITIALIZE IT, ACCORDING TO
% THE EXAMPLE FOUND IN http://sumo-sim.org/userdoc/Tutorials/TraCI4Traffic_Lights.html

scenarioPath = './inter_palmas/tls_actuated/inter_palmas_actuated.sumocfg ';

[traciVersion,sumoVersion] = traci.start(['sumo -c ' '"' scenarioPath '"' ' --start']);
traci.close();
fprintf('SUMO version: %s\n TraCI version: %d\n',sumoVersion,traciVersion);
`
**I got the following output:**
SUMO version: SUMO 1.2.0
TraCI version: 20

**Comment by mnour94** [comment]
did you happen to find a solution for this issue? I have the same problem.

**Comment by kelly7707** [comment]
any solution? I also have the same problem. Thanks in advance.

**Comment by Han21-yes** [comment]
Try to restart Matlab to make the new static Java path takes effect.
